### ISSUE TITLE
Would Like to Be Able to Control Classes, IDs, Rel and Data Attributes on Both the List Item and Link Anchor

### ISSUE THREAD

**Issue by lynnwallenstein** [bruce/goose#1]
I am using [twitter bootstrap's drop down JS](http://twitter.github.com/bootstrap/javascript.html#dropdowns) for a navigation menu and want to use Goose to generate the links for me. In order to do so i need to be able to control the classes and data attributes on not only the list items (which I can do currently) but also the link it generates.

My source: https://gist.github.com/2219236

What it currently generates using Goose:  https://gist.github.com/2219265

What I need it to generate to work:  https://gist.github.com/2219279

... basically I need to add class="dropdown-toggle" data-toggle="dropdown" to the link anchor, however I also still need to leep the class of dropdown on the list item.

**Comment by bruce** [comment]
Now if you dont pass a URL parameter it won't try to make a link for you, and you can create it how you like at the top of your `nav_to` block, e.g. modifying your original:

```
<ul class="nav">
  <li class="vertical-divider"></li>
  <%= nav_to ('Home', root_path) %>
  <%= nav_to ('Docs', docs_path) %>
  <%= nav_to "Coding Styles"  do %>
    <%= link_to "Coding Styles", "#", 'data-toggle' => 'dropdown', :class => "dropdown" %>
    <ul class="dropdown-menu">
      <%= nav_to "CSS/Sass", :controller => "coding_styles", :action => "css" %>
      <%= nav_to "HTML", :controller => "coding_styles", :action => "html" %>
      <%= nav_to "JavaScript/CoffeeScript", :controller => "coding_styles", :action => "javascript" %>
      <%= nav_to "Ruby", :controller => "coding_styles", :action => "ruby" %>
    </ul>
    <% end %>
</ul>
```

Unfortunately there's some duplication ("Coding Styles" ... "Coding Styles") since `nav_to` uses the text for determining the active item (as passed to `nav_at`), but we can work on making the API better for this edge case. I'm reticent to just support passing two ad hoc customization hashes to `nav_to` (for the wrapper element and link), but I'm also aware the single config file approach is a bit too inflexible for complex interfaces.

Let me know if the above in HEAD works for you and I'll push a new release.

**Comment by lynnwallenstein** [comment]
Worked!
